# Generated by Django 5.2.5 on 2025-08-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='details_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
