# Generated by Django 5.2.5 on 2025-08-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('details_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
