# Generated by Django 5.2.5 on 2025-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
