# Generated by Django 5.2.5 on 2025-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_services_details_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
