# Generated by Django 5.2.5 on 2025-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrip',
            name='detials_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
