# Generated by Django 5.2.5 on 2025-08-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_detials_url_domestictrip_details_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationaltrip',
            name='details_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
