# Generated by Django 5.2.5 on 2025-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_internationaltrip_excluded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestictrip',
            name='itinerary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
