# Generated by Django 5.2.5 on 2025-08-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_domestictrip_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationaltrip',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
