# Generated by Django 5.2.5 on 2025-08-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_domestictrip_content_internationaltrip_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domestictrip',
            name='content',
        ),
        migrations.RemoveField(
            model_name='internationaltrip',
            name='content',
        ),
    ]
