# Generated by Django 5.2.5 on 2025-08-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
