# Generated by Django 5.2.5 on 2025-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
