# Generated by Django 5.2.5 on 2025-08-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_internationaltrip_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
