# Generated by Django 5.2.5 on 2025-08-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_domestictrip_detials_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domestictrip',
            old_name='detials_url',
            new_name='details_url',
        ),
    ]
