# Generated by Django 5.2.5 on 2025-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_internationaltrip_details_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrip',
            name='excluded',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domestictrip',
            name='included',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domestictrip',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domestictrip',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
