# Generated by Django 5.2.5 on 2025-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_domestictrip_excluded_domestictrip_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationaltrip',
            name='excluded',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationaltrip',
            name='included',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationaltrip',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationaltrip',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
