# Generated by Django 5.2.5 on 2025-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_internationaltrip_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrip',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internationaltrip',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
