# Generated by Django 5.2.5 on 2025-09-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0005_map_roles'),
        ('RBAC', '0006_alter_userprofile_role'),
    ]

    operations = [
    ]
