# Generated by Django 5.2.5 on 2025-10-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0007_merge_0005_map_roles_0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='description',
        ),
    ]
