# Generated by Django 5.2.5 on 2025-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0008_remove_permission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
